using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Query_Creator_for_Excel
{
    public partial class Help : Form
    {
        public Help()
        {
            InitializeComponent();
            CultureInfo ci = CultureInfo.InstalledUICulture;
            if (ci.TwoLetterISOLanguageName == "es")
            {
                Instructions.Text = "Para utilizar el programa de manera correcta el documento de Excel debera " +
                        "tener el siguiente formato: " + Environment.NewLine + Environment.NewLine +
                        "1. Aqui debera contenerse el nombre de la Columna de Clave Primaria de ser un UPDATE o " +
                        "cualquier otra columna en caso de un query INSERT." + Environment.NewLine +
                        "2. Aqui deberan ir los nombres de las demas columnas a modificar o insertar." + Environment.NewLine +
                        "3. En esta columna van las llaves primarias." + Environment.NewLine +
                        "4. En estas columnas van los datos de las columnas restantes." + Environment.NewLine +
                        "5. Aqui debera pegarse la formula creada por el programa." + Environment.NewLine + Environment.NewLine +
                        "Despues de realizar de pegar la formula en el campo 5 debera copiar esa formula y " +
                        "pegarla en las lineas en las que tambien se quiere generar queries.";
            }
            else
            {
                Instructions.Text = "To be able to generate the formula correctly the document needs " +
                        "to be in the following format: " + Environment.NewLine + Environment.NewLine +
                        "1. The first Cell should be the Primary key for the UPDATE queries " +
                        "(is not important if you're doing an insert query)" + Environment.NewLine +
                        "2. These should be the rest of the names of the columns. " + Environment.NewLine +
                        "3. This column should contain the value of the primary keys." + Environment.NewLine +
                        "4. These should contain the rest of the values for the columns." + Environment.NewLine +
                        "5. In this cell you should paste the formula this program generates." + Environment.NewLine + Environment.NewLine +
                        "After pasting the formula generated by this program you should copy that cell " +
                        "and paste it in the other cells below it.";
                this.Text = "Help";
            }
                
        }

    }
}
